# Application YAML
spring:
  application:
    name: phforeclosures

  datasource:
    url: jdbc:sqlite:phforeclosures.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        format_sql: true
